args: !!python/object/new:easydict.EasyDict
  dictitems:
    K: 1
    accum_grad: 2
    batch_size: 32
    depth: 4
    dim: 1024
    dtype: float32
    eval_every: 5
    gnn_type: GAT
    heads: 2
    in_dim: 21
    loader_workers: 2
    lr: 0.0005
    lr_factor: 0.3
    max_epochs: 1000
    n: 10
    need_one_hot: true
    num_classes: 10
    num_test_samples: 700
    num_train_samples: 7000
    optim_type: Adam
    out_dim: 10
    repeat: 1
    seed: 0
    star_variant: connected
    task_type: two
    use_activation: true
    use_layer_norm: true
    use_residual: true
    use_virtual_nodes: false
    val_batch_size: 1024
    vn_residual: true
    wd: 0.0
  state:
    K: 1
    accum_grad: 2
    batch_size: 32
    depth: 4
    dim: 1024
    dtype: float32
    eval_every: 5
    gnn_type: GAT
    heads: 2
    in_dim: 21
    loader_workers: 2
    lr: 0.0005
    lr_factor: 0.3
    max_epochs: 1000
    n: 10
    need_one_hot: true
    num_classes: 10
    num_test_samples: 700
    num_train_samples: 7000
    optim_type: Adam
    out_dim: 10
    repeat: 1
    seed: 0
    star_variant: connected
    task_type: two
    use_activation: true
    use_layer_norm: true
    use_residual: true
    use_virtual_nodes: false
    val_batch_size: 1024
    vn_residual: true
    wd: 0.0
task_id: 0
